components:
  schemas:
    Role:
      type: object
      properties:
        _id:
          type: string
        name:
          type: string
        description:
          type: string
        permissions:
          type: array
          items:
            type: string
        isActive:
          type: boolean
        createdAt:
          type: number
        createdBy:
          type: string
        lastModifiedAt:
          type: number
        lastModifiedBy:
          type: string
