components:
  schemas:
    User:
      type: object
      properties:
        _id:
          type: string
        fullName:
          type: string
        email:
          type: string
        phoneNo:
          type: string
        avatarUrl:
          type: string
        dob:
          type: string
        address:
          type: string
        gender:
          type: string
          enum: [MALE, FEMALE, OTHER]
        numberOfPets:
          type: number
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        loginType:
          type: string
          enum: [FACEBOOK, GOOGLE, APPLE]
        firebaseId:
          type: string
        isActive:
          type: boolean
        createdAt:
          type: number
        createdBy:
          type: string
        lastModifiedAt:
          type: number
        lastModifiedBy:
          type: string
