openapi: 3.0.0
info:
  title: Pets Hotel API
  description: API
  contact:
    email: tienloinguyen22@gmail.com
  license:
    name: Pets Hotel
    url: https://petshotel.vn/privacy-policy
  version: 0.1.0
servers:
  - url: http://localhost:3000/api
